### ISSUE TITLE
Does Now Keep Icon

### ISSUE THREAD

**Issue by FireController1847** [s-h-a-d-o-w/create-nodew-exe#1]
If you try and do this to an exe that has an icon, it will remove the icon.
![explorer_2018-12-31_15-23-26](https://user-images.githubusercontent.com/16494272/50568498-05d51800-0d10-11e9-8cb4-b3ac9ea7acb9.jpg)

**Comment by s-h-a-d-o-w** [comment]
That's OK.
While it's not directly related to `create-nodew-exe`, I was experiencing issues like that while working on Spotify Ad Blocker myself. So I updated the README here as a preventive measure. If you're not yet aware of `ie4uinit`, I recommend you [check it out](https://github.com/s-h-a-d-o-w/create-nodew-exe#notes).

**Comment by FireController1847** [comment]
Thanks!
