### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by RenChaoX** [s-h-a-d-o-w/create-nodew-exe#2]
I don't know how to use it.Has been an error.

```bash
create-nodew-exe express-demo/main.js test.exe
```
Wrong reasons:   Error: Invalid EXE: express-demo/main.js

**Comment by s-h-a-d-o-w** [comment]
See https://github.com/s-h-a-d-o-w/create-nodew-exe#create-nodew-exe:
> Creates an executable based on node.exe

You're trying to use it on a .js file instead.
I think what you're looking for may be [pkg](https://github.com/zeit/pkg) or [nexe](https://github.com/nexe/nexe).
